name: Build VSCode Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Clean install dependencies
      run: |
        rm -rf node_modules
        npm install
    
    - name: Compile extension
      run: npm run compile
    
    - name: Install vsce
      run: npm install -g @vscode/vsce
    
    - name: Package extension
      run: vsce package --no-dependencies
    
    - name: Upload extension artifact
      uses: actions/upload-artifact@v4
      with:
        name: aws-sso-login-extension
        path: "*.vsix"
        if-no-files-found: error
