name: Build VSCode Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:
    outputs:
      vsix-path:
        description: "Path to the built VSIX file"
        value: ${{ jobs.build.outputs.vsix-path }}

jobs:
  # Run lint and test workflow first
  lint-test:
    uses: ./.github/workflows/lint-test.yml

  build:
    needs: lint-test
    runs-on: ubuntu-latest
    outputs:
      vsix-path: ${{ steps.package-extension.outputs.vsix-path }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    
    - name: Cache dependencies
      uses: actions/cache@v4
      id: npm-cache
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    
    - name: Install dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm ci
    
    - name: Compile extension
      run: npm run compile
    
    - name: Package extension
      id: package-extension
      run: |
        npx @vscode/vsce package --no-dependencies
        echo "vsix-path=$(ls *.vsix)" >> $GITHUB_OUTPUT
    
    - name: Upload extension artifact
      uses: actions/upload-artifact@v4
      with:
        name: aws-sso-login-extension
        path: "*.vsix"
        if-no-files-found: error
        retention-days: 7
