name: Build VSCode Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Compile extension
      run: npm run compile
    
    - name: Package extension
      run: npm run package
    
    - name: Upload extension artifact
      uses: actions/upload-artifact@v3
      with:
        name: aws-sso-login-extension
        path: "*.vsix"
        if-no-files-found: error
