name: Release VSCode Extension

on:
  push:
    tags:
      - 'v*' # Run workflow on version tags, e.g. v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for creating GitHub releases

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Clean install dependencies
      run: npm install
    
    - name: Compile extension
      run: npm run compile
    
    - name: Install vsce
      run: npm install -g @vscode/vsce
    
    - name: Package extension
      run: vsce package --no-dependencies
      
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: AWS SSO Login v${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        files: "*.vsix"
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    # Uncomment the following step if you want to publish to VSCode Marketplace
    # - name: Publish to Visual Studio Marketplace
    #   run: vsce publish -p ${{ secrets.VSCE_PAT }}
